# -*- coding: utf-8 -*-
# data_verifier.py
import os

# --- First Principles ---
TRIGRAM_STRUCTURES = {
    '乾': (1, 1, 1), '兌': (0, 1, 1), '離': (1, 0, 1), '震': (0, 0, 1),
    '巽': (1, 1, 0), '坎': (0, 1, 0), '艮': (1, 0, 0), '坤': (0, 0, 0),
}
HEXAGRAM_COMPOSITION = {
    "乾": ("乾", "乾"), "坤": ("坤", "坤"), "屯": ("震", "坎"), "蒙": ("坎", "艮"),
    "需": ("乾", "坎"), "訟": ("坎", "乾"), "師": ("坤", "坎"), "比": ("坎", "坤"),
    "小畜": ("乾", "巽"), "履": ("兌", "乾"), "泰": ("乾", "坤"), "否": ("坤", "乾"),
    "同人": ("離", "乾"), "大有": ("乾", "離"), "謙": ("艮", "坤"), "豫": ("坤", "震"),
    "隨": ("震", "兌"), "蠱": ("巽", "艮"), "臨": ("兌", "坤"), "觀": ("坤", "巽"),
    "噬嗑": ("震", "離"), "賁": ("離", "艮"), "剝": ("坤", "艮"), "復": ("震", "坤"),
    "无妄": ("震", "乾"), "大畜": ("乾", "艮"), "頤": ("震", "艮"), "大過": ("巽", "兌"),
    "坎": ("坎", "坎"), "離": ("離", "離"), "咸": ("艮", "兌"), "恒": ("巽", "震"),
    "遯": ("艮", "乾"), "大壯": ("乾", "震"), "晉": ("坤", "離"), "明夷": ("離", "坤"),
    "家人": ("離", "巽"), "睽": ("兌", "離"), "蹇": ("艮", "坎"), "解": ("坎", "震"),
    "損": ("兌", "艮"), "益": ("震", "巽"), "夬": ("乾", "兌"), "姤": ("巽", "乾"),
    "萃": ("坤", "兌"), "升": ("巽", "坤"), "困": ("坎", "兌"), "井": ("巽", "坎"),
    "革": ("離", "兌"), "鼎": ("巽", "離"), "震": ("震", "震"), "艮": ("艮", "艮"),
    "漸": ("艮", "巽"), "歸妹": ("兌", "震"), "豐": ("離", "震"), "旅": ("艮", "離"),
    "巽": ("巽", "巽"), "兌": ("兌", "兌"), "渙": ("坎", "巽"), "節": ("兌", "坎"),
    "中孚": ("兌", "巽"), "小過": ("艮", "震"), "既濟": ("離", "坎"), "未濟": ("坎", "離")
}

# --- Generation Logic ---
def generate_correct_structure_data():
    correct_hex_structure = {}
    # Use sorted items for a consistent order
    for hex_name, (lower_trigram_name, upper_trigram_name) in sorted(HEXAGRAM_COMPOSITION.items()):
        lower_lines = TRIGRAM_STRUCTURES[lower_trigram_name]
        upper_lines = TRIGRAM_STRUCTURES[upper_trigram_name]
        full_structure = list(lower_lines + upper_lines)
        correct_hex_structure[hex_name] = full_structure
    return correct_hex_structure

# --- Main Execution ---
if __name__ == "__main__":
    final_correct_data = generate_correct_structure_data()
    
    output_file_path = os.path.join("C:\\fate2", "correct_hex_data.py")
    with open(output_file_path, "w", encoding="utf-8") as f:
        f.write("# This file was auto-generated by data_verifier.py\n")
        f.write("# Correct HEXAGRAM_STRUCTURE data (1=Yang, 0=Yin, bottom-to-top)\n")
        f.write("HEXAGRAM_STRUCTURE = {\n")
        
        formatted_items = []
        for name, structure in final_correct_data.items():
            formatted_items.append(f"    '{name}': {structure}")
        
        f.write(",\n".join(formatted_items))
        f.write("\n}")
        
    print(f"Correct data has been written to {output_file_path}")